-- =============================================
-- TẠO CƠ SỞ DỮ LIỆU
-- =============================================
-- Xóa cơ sở dữ liệu nếu đã tồn tại
--drop database if exists QUANLYCLB_UTE
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'QUANLYCLB_UTE')
BEGIN
    USE master; -- Chuyển sang cơ sở dữ liệu master để có thể xóa được cơ sở dữ liệu khác
    ALTER DATABASE QUANLYCLB_UTE SET SINGLE_USER WITH ROLLBACK IMMEDIATE; -- Ngắt mọi kết nối
    DROP DATABASE QUANLYCLB_UTE; -- Xóa cơ sở dữ liệu
END
CREATE DATABASE QUANLYCLB_UTE;
GO
USE QUANLYCLB_UTE;
GO

-- =============================================
-- 1. TẠO CÁC BẢNG DANH MỤC ĐỘC LẬP (KHÔNG CÓ KHÓA NGOẠI)
-- =============================================

CREATE TABLE Khoa (
    maKhoa CHAR(13) PRIMARY KEY,
    tenKhoa NVARCHAR(100) NOT NULL,
    tenVietTat NVARCHAR(10),
    soDienThoai VARCHAR(15),
    email VARCHAR(50)
);

CREATE TABLE DONVIQUANLY (
    maDVQL CHAR(13) PRIMARY KEY,
    tenDVQL NVARCHAR(255) NOT NULL,
    emailLienHien VARCHAR(50),
    soDienThoai VARCHAR(15)
);

CREATE TABLE VAI_TRO (
    VaiTroID CHAR(13) PRIMARY KEY,
    tenVaiTro NVARCHAR(50) NOT NULL,
    moTa NVARCHAR(255),
    quyen NVARCHAR(255),
    trangThai BIT DEFAULT 1
);

CREATE TABLE TAI_KHOAN (
    MaND CHAR(13) PRIMARY KEY,
    hoTen NVARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    soDienThoai VARCHAR(15),
    ngaySinh DATE,
    gioiTinh NVARCHAR(10),
    anhDaiDien NVARCHAR(255),
    trangThai BIT DEFAULT 1,
    lanDangNhapCuoi DATETIME
);

-- =============================================
-- 2. TẠO CÁC BẢNG CÓ KHÓA NGOẠI CẤP 1
-- =============================================

CREATE TABLE Lop (
    maLop CHAR(13) PRIMARY KEY,
    maKhoa CHAR(13),
    tenLop NVARCHAR(50) NOT NULL,
    nienKhoa NVARCHAR(20),
    siSo INT,
    trangThai NVARCHAR(20),
    CONSTRAINT FK_Lop_Khoa FOREIGN KEY (maKhoa) REFERENCES Khoa(maKhoa) 
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE NGUOIDUNG_VAITRO (
    MaND CHAR(13),
    VaiTroID CHAR(13),
    GhiChu NVARCHAR(255),
    PRIMARY KEY (MaND, VaiTroID),
    CONSTRAINT FK_NDVT_TaiKhoan FOREIGN KEY (MaND) REFERENCES TAI_KHOAN(MaND) 
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_NDVT_VaiTro FOREIGN KEY (VaiTroID) REFERENCES VAI_TRO(VaiTroID) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SINHVIEN (
    maSV CHAR(13) PRIMARY KEY,
    maLop CHAR(13),
    diemRenLuyen INT DEFAULT 0,
    CONSTRAINT FK_SV_TaiKhoan FOREIGN KEY (maSV) REFERENCES TAI_KHOAN(MaND) 
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SV_Lop FOREIGN KEY (maLop) REFERENCES Lop(maLop) 
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE CANBO (
    maCanBo CHAR(13) PRIMARY KEY,
    maDVQL CHAR(13),
    chucVu NVARCHAR(50),
    trangThai BIT DEFAULT 1,
    CONSTRAINT FK_CB_TaiKhoan FOREIGN KEY (maCanBo) REFERENCES TAI_KHOAN(MaND) 
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_CB_DVQL FOREIGN KEY (maDVQL) REFERENCES DONVIQUANLY(maDVQL) 
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE CAULACBO (
    MaCLB CHAR(13) PRIMARY KEY,
    maDVQL CHAR(13),
    TenCLB NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(MAX),
    Logo NVARCHAR(255),
    NgayThanhLap DATE,
    SoThanhVienToiDa INT,
    LinhVuc NVARCHAR(50),
    TrangThai NVARCHAR(50),
    CONSTRAINT FK_CLB_DVQL FOREIGN KEY (maDVQL) REFERENCES DONVIQUANLY(maDVQL) 
        ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE TAI_SAN (
    MaTS CHAR(13) PRIMARY KEY,
    MaDVQL CHAR(13),
    TenTS NVARCHAR(255) NOT NULL,
    SoLuongTong INT NOT NULL,
    CONSTRAINT FK_TS_DVQL FOREIGN KEY (MaDVQL) REFERENCES DONVIQUANLY(maDVQL) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- =============================================
-- 3. TẠO CÁC BẢNG NGHIỆP VỤ LÕI (CẤP 2)
-- =============================================

CREATE TABLE TAI_CHINH (
    MaTC CHAR(13) PRIMARY KEY,
    MaCLB CHAR(13),
    TenTaiChinh NVARCHAR(100),
    Nam INT,
    TongThu DECIMAL(18,2) DEFAULT 0,
    TongChi DECIMAL(18,2) DEFAULT 0,
    NgayBatDau DATE,
    NgayKetThuc DATE,
    TrangThai NVARCHAR(50),
    NgayTao DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_TC_CLB FOREIGN KEY (MaCLB) REFERENCES CAULACBO(MaCLB) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE THANH_VIEN (
    MaTV CHAR(13) PRIMARY KEY,
    MaCLB CHAR(13),
    MaND CHAR(13),
    VaiTroCLB NVARCHAR(50),
    NgayThamGia DATE,
    NgayRoi DATE,
    LyDoRoi NVARCHAR(200),
    DiemDongGop FLOAT DEFAULT 0,
    GhiChu NVARCHAR(255),
    TrangThai NVARCHAR(50),
    CONSTRAINT FK_TV_CLB FOREIGN KEY (MaCLB) REFERENCES CAULACBO(MaCLB) 
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_TV_TaiKhoan FOREIGN KEY (MaND) REFERENCES TAI_KHOAN(MaND) 
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE SU_KIEN (
    MaSK CHAR(13) PRIMARY KEY,
    MaCLB CHAR(13),
    TenSK NVARCHAR(150) NOT NULL,
    MoTa NVARCHAR(MAX),
    ThoiGianBatDau DATETIME,
    ThoiGianKetThuc DATETIME,
    DiaDiem NVARCHAR(200),
    SoNguoiToiDa INT,
    ChiPhiDuKien DECIMAL(18,2),
    LoaiSK NVARCHAR(50),
    TrangThai NVARCHAR(50),
    NgayTao DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_SK_CLB FOREIGN KEY (MaCLB) REFERENCES CAULACBO(MaCLB) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- =============================================
-- 4. TẠO CÁC BẢNG CHI TIẾT & LỊCH SỬ (CẤP 3)
-- =============================================

CREATE TABLE LICHSU_THANHVIEN (
    MaLS CHAR(13) PRIMARY KEY,
    MaTV CHAR(13),
    HanhDong NVARCHAR(50),
    VaiTroCu NVARCHAR(50),
    VaiTroMoi NVARCHAR(50),
    LyDo NVARCHAR(200),
    NgayThayDoi DATETIME DEFAULT GETDATE(),
    GhiChu NVARCHAR(255),
    CONSTRAINT FK_LSTV_TV FOREIGN KEY (MaTV) REFERENCES THANH_VIEN(MaTV) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE NHIEM_VU (
    MaNV CHAR(13) PRIMARY KEY,
    MaCLB CHAR(13),
    MaSK CHAR(13),
    TenNV NVARCHAR(200) NOT NULL,
    MoTa NVARCHAR(MAX),
    MaTV_PhuTrach CHAR(13),
    NguoiGiaoID CHAR(13),
    DoUuTien NVARCHAR(50),
    TienDo INT DEFAULT 0,
    NgayBatDau DATE,
    HanChot DATETIME,
    NgayHoanThanh DATETIME,
    TrangThai NVARCHAR(50),
    CONSTRAINT FK_NV_CLB FOREIGN KEY (MaCLB) REFERENCES CAULACBO(MaCLB) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT FK_NV_SK FOREIGN KEY (MaSK) REFERENCES SU_KIEN(MaSK) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_NV_TVPT FOREIGN KEY (MaTV_PhuTrach) REFERENCES THANH_VIEN(MaTV) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT FK_NV_TaiKhoan FOREIGN KEY (NguoiGiaoID) REFERENCES TAI_KHOAN(MaND) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE PHAN_CONG_NHIEMVU (
    MaPC CHAR(13) PRIMARY KEY,
    MaNV CHAR(13),
    MaTV CHAR(13),
    TienDoCaNhan INT DEFAULT 0,
    NgayPhanCong DATETIME DEFAULT GETDATE(),
    NgayHoanThanh DATETIME,
    GhiChu NVARCHAR(MAX),
    TrangThai NVARCHAR(50),
    CONSTRAINT FK_PC_NV FOREIGN KEY (MaNV) REFERENCES NHIEM_VU(MaNV) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_PC_TV FOREIGN KEY (MaTV) REFERENCES THANH_VIEN(MaTV) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE DANGKY_SUKIEN (
    MaDK CHAR(13) PRIMARY KEY,
    MaSK CHAR(13),
    MaND CHAR(13),
    NgayDangKy DATETIME DEFAULT GETDATE(),
    NguoiDuyetID CHAR(13),
    LyDoDangKy NVARCHAR(300),
    NgayDuyet DATETIME,
    TrangThai NVARCHAR(50),
    GhiChu NVARCHAR(255),
    CONSTRAINT FK_DK_SK FOREIGN KEY (MaSK) REFERENCES SU_KIEN(MaSK) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_DK_TaiKhoan FOREIGN KEY (MaND) REFERENCES TAI_KHOAN(MaND) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT FK_DK_NguoiDuyet FOREIGN KEY (NguoiDuyetID) REFERENCES TAI_KHOAN(MaND) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE THONG_BAO (
    MaTB CHAR(13) PRIMARY KEY,
    MaCLB CHAR(13),
    TieuDe NVARCHAR(200) NOT NULL,
    NoiDung NVARCHAR(MAX),
    NguoiGuiID CHAR(13),
    SoNguoiNhan INT,
    LoaiTB NVARCHAR(50),
    NgayGui DATETIME DEFAULT GETDATE(),
    TrangThai NVARCHAR(50),
    CONSTRAINT FK_TB_CLB FOREIGN KEY (MaCLB) REFERENCES CAULACBO(MaCLB) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_TB_TaiKhoan FOREIGN KEY (NguoiGuiID) REFERENCES TAI_KHOAN(MaND) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE HOSO (
    MaHoSo CHAR(13) PRIMARY KEY,
    maCLB CHAR(13),
    maNguoiGui CHAR(13),
    maNguoiDuyet CHAR(13),
    loaiHoSo NVARCHAR(50),
    TieuDe NVARCHAR(200) NOT NULL,
    NoiDung NVARCHAR(MAX),
    FileDinhKem NVARCHAR(255),
    TrangThai NVARCHAR(50),
    NgayGui DATETIME DEFAULT GETDATE(),
    NgayDuyet DATETIME,
    LyDoTuChoi NVARCHAR(300),
    CONSTRAINT FK_HS_CLB FOREIGN KEY (maCLB) REFERENCES CAULACBO(MaCLB) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_HS_NguoiGui FOREIGN KEY (maNguoiGui) REFERENCES TAI_KHOAN(MaND) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT FK_HS_NguoiDuyet FOREIGN KEY (maNguoiDuyet) REFERENCES TAI_KHOAN(MaND) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE KHEN_THUONG_KY_LUAT (
    MaKTKL CHAR(13) PRIMARY KEY,
    MaND CHAR(13),
    MaCLB CHAR(13),
    Loai NVARCHAR(50),
    HinhThuc NVARCHAR(100),
    DiemThayDoi FLOAT,
    LyDo NVARCHAR(MAX),
    NguoiQuyetDinhID CHAR(13),
    NgayQuyetDinh DATETIME,
    NgayHieuLuc DATE,
    FileMinhChung NVARCHAR(255),
    TrangThai NVARCHAR(50),
    CONSTRAINT FK_KTKL_TaiKhoan FOREIGN KEY (MaND) REFERENCES TAI_KHOAN(MaND) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT FK_KTKL_CLB FOREIGN KEY (MaCLB) REFERENCES CAULACBO(MaCLB) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_KTKL_QuyetDinh FOREIGN KEY (NguoiQuyetDinhID) REFERENCES TAI_KHOAN(MaND) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE PHIEU_MUON_TRA (
    MaPhieu CHAR(13) PRIMARY KEY,
    MaCLB CHAR(13),
    MaSK CHAR(13),
    NguoiMuonID CHAR(13),
    NgayTaoPhieu DATE DEFAULT GETDATE(),
    NgayTraDuKien DATE,
    trangThaiPhieu NVARCHAR(50),
    CONSTRAINT FK_PMT_CLB FOREIGN KEY (MaCLB) REFERENCES CAULACBO(MaCLB) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_PMT_SK FOREIGN KEY (MaSK) REFERENCES SU_KIEN(MaSK) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT FK_PMT_NguoiMuon FOREIGN KEY (NguoiMuonID) REFERENCES TAI_KHOAN(MaND) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE CHI_TIET_PHIEU_MUON (
    MaPhieu CHAR(13),
    MaTS CHAR(13),
    SoLuongMuon INT NOT NULL,
    tinhTrang NVARCHAR(100),
    PRIMARY KEY (MaPhieu, MaTS),
    CONSTRAINT FK_CTPM_Phieu FOREIGN KEY (MaPhieu) REFERENCES PHIEU_MUON_TRA(MaPhieu) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_CTPM_TaiSan FOREIGN KEY (MaTS) REFERENCES TAI_SAN(MaTS) ON UPDATE NO ACTION ON DELETE NO ACTION
);
GO